//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.Application.DocumentsGenerator.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Logon", ReplyAction="http://tempuri.org/IAuthenticationService/LogonResponse")]
        BG.DAL.AuthModels.LogonResult Logon(BG.DAL.AuthModels.LogonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Logon", ReplyAction="http://tempuri.org/IAuthenticationService/LogonResponse")]
        System.Threading.Tasks.Task<BG.DAL.AuthModels.LogonResult> LogonAsync(BG.DAL.AuthModels.LogonInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : BG.Application.DocumentsGenerator.ServiceReference.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<BG.Application.DocumentsGenerator.ServiceReference.IAuthenticationService>, BG.Application.DocumentsGenerator.ServiceReference.IAuthenticationService {

        public AuthenticationServiceClient() { }


        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BG.DAL.AuthModels.LogonResult Logon(BG.DAL.AuthModels.LogonInfo info) {
            return base.Channel.Logon(info);
        }
        
        public System.Threading.Tasks.Task<BG.DAL.AuthModels.LogonResult> LogonAsync(BG.DAL.AuthModels.LogonInfo info) {
            return base.Channel.LogonAsync(info);
        }
    }
}
